### ISSUE TITLE
:D

### ISSUE THREAD

**Issue by dhammma** [coop2work/JSninja#1]
![](https://i.giphy.com/media/p4NLw3I4U0idi/giphy.webp)

**Comment by dmitriys-lits** [comment]
@dmitriys-lits you can close it only after task completing, reopen, please

**Comment by coop2work** [comment]
![1_XpdVmHbfJsDzZ_GqmOEIWg_1](https://user-images.githubusercontent.com/49642164/56232292-16c05400-6089-11e9-8b11-dad232c84b42.gif)

**Comment by coop2work** [comment]
@dmitriys-lits fixed, please check.

**Comment by dhammma** [comment]
@coop2work nice work 👍
